# Generated by Django 2.2 on 2019-04-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('time_modification', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=0)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
                ('contenttime', models.DateTimeField(auto_now_add=True)),
                ('artid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='acation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cation'),
        ),
        migrations.AddField(
            model_name='article',
            name='atag',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
